alinebastos/remote

- README.md
Add Cycloid in the list of companies which appear in the README.
> README: Add Cycloid company

- README.md
> Add zapier to list

- README.md
Added Leanwork to the list of companies with remote positions ❤️
> Added Leanwork

- README.md
Doist is a full-remote company. Here's more about them: [https://doist.com/about-us/](https://doist.com/about-us/).
> Adds Doist (the makes of Todoist app) to the list

- README.md
> 7 new job portals added.

- README.md
> Including Impulso

- README.md
Added two new companies at Brazilian label
> Update README. md

- README.md
It has the ability to search for remote jobs hiring from your location. This is useful because many remote jobs only hire from specific countries.
> Add Remote Tech Jobs by Standard Resume

- README.md
Some of the companies I know who have vacancies for remote work not only in the development area but mainly. One of them is where I work. (Mundiale)
> Adding some companies to list

- README.md
Adicionei mais algumas empresas brasileiras. :smile:
> New companies to list (Brazil)

- README.md
Added XP investimentos in the list of companies with remote vacancies
> XP Investimentos

- README.md
> Ordem lista

- README.md
Oie! eu percebi muitos dos links na lista de empresas brasileiras não estavam direcionando para a página de vagas delas, então eu alterei isso. Eu também fiz uma correçãozinha no inglês 😄
> Changes the link to some of the pages and fix english

- README.md
Adding Sinqia to the topic Brazilian companies
> Adding Sinqia to the topic Brazilian companies

- README.md
Adicionei o github do Back-end Brasil com diversas vagas remotas (ou não)
> Add Back-end Brasil

- README.md
At accenture we have 96 open positions for different technologies
> add remote accenture jobs

- README.md
> add thoughtworks jobs

- README.md
> adding dextra companie

- CONTRIBUTING.md
- README.md
- REFERENCES.md
Oi Aline! Fiz o que tu pediu quanto as empresas que estavam no [tweet do HugoRoger](https://twitter.com/AlineBastos/status/1325455489703030788):
Também aproveitei pra adicionar algumas que lembrei (APOIA.se, e-Core, Groundbreaker e Meta), criei um CONTRIBUTING.md com informações pra ajudar quem quiser contribuir e um REFERENCES.md para deixar referenciado de onde veio o link (acredito que é interessante).
Veja o que acha. Se não curtir, dá pra tirar o que tiver de adicional.
Ah, também interessante mudarmos a branch master pra main!
Abraços!
> Adiciona novas empresas (tweet do HugoRoger) e outras coisas

- README.md
Add new link in Job Portals list
> feat: add new link to list
